logging:
  level:
    root: WARN
    ru.jegensomme.citingvkbot: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    visibility:
      field: none
      getter: any
      setter: any
      is-getter: any
